### ISSUE TITLE
Move unhide all logic to juicy-tile-list and juicy-tile-grid

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Launcher#129]
The unhide all logic is inside `juicy-tile-editor-form`, which is not very correct.

The method should be moved to the tile containers (`juicy-tile-list` and `juicy-tile-grid`) and they should recursively call the method of own children.

What would be a good way to don't create two exactly the same methods in `juicy-tile-list` and `juicy-tile-grid`?

References to: https://github.com/Polyjuice/Launcher/issues/124

**Comment by warpech** [comment]
`juicy-tile-grid` extends `juicy-tile-list`, so it is sufficient to put it to `juicy-tile-list`. 

@tomalec do you agree?

**Comment by miyconst** [comment]
I guess that *Unhide all* button should unhide all of the items inside, including all children.

In the first implementation I foreach through `this.allItems` and unhide them all. Then, on the demo page I saw nesting of `juicy-tile-list` and remade the method to not only unhide own items, but also unhide items of nested `juicy-tile-list` and `juicy-tile-grid`.

If the method is moved to `juicy-tile-list` then it will be aware of `juicy-tile-grid` which is not good.

There should be some nice way to do that, probably I just miss it.

**Comment by tomalec** [comment]
I believe that due to CustomElements encapsulation idea, single `juicy-tile-list` should not mess with others, and editor should be the one that is aware that hiding a tile should also hide nested tiles.

**Comment by tomalec** [comment]
Another thing is that if parent tiles hides tile containing another partial with nested tiles, it would be enought to hide it visually, and would not hide entire partial which could be used elsewhere.

**Comment by tomalec** [comment]
Do we want to unhide tiles from not visilbe juicy tile lists as weel, let say those from hidden workspaces?

**Comment by miyconst** [comment]
> single juicy-tile-list should not mess with others

Absolutely agree.

It might be two methods:

1. A method inside `juicy-tile-list` which unhides only own items.
2. A method inside `juicy-tile-editor` which selects all of the `juicy-tile-list` and `juicy-tile-grid` and then invokes the method 1.

What are the hidden workspaces? I think the *Unhide all* button should make visible every possible tile on the page.

**Comment by tomalec** [comment]
Hidden workspaces:
 1. Run Launcher, App1, App2
 2. From Launcher's launchpad (home screen) go to [App1](http://localhost:8080/App1) - App1 output wrapped in `juicy-tile-list`will be added to DOM
 3. Go to Launcher's home
 3. Ggo to [App2](http://localhost:8080/App2) - App1 workspace will get hidden, App2 output wrapped in `juicy-tile-list`will be added to DOM

Now juicy-tile-editor` shows `juicy-tile-list`'s from Launchpad, App1, and App2 even if you see only App2 output.

**Comment by miyconst** [comment]
Okay.. I don't understand why the workspace is hidden, and not removed, but in this case unhide button should show tiles in visible workspaces only.

**Comment by warpech** [comment]
> Okay.. I don't understand why the workspace is hidden, and not removed, but in this case unhide button should show tiles in visible workspaces only.

Workspaces are like windows in desktop OS. Assume you open 3 programs as full screen windows. Each of the windows is called "workspace" in Launcher.

The currently visible window is `display: block` while the windows behind it are `display: hidden`.

---

`juicy-tiles-tree` shows all elements in all windows and does not care if they are visible or not. 

Maybe it should check if elements are displayed? Meaning - while building the tree it should only display a leaf if the element and none of its parents is `display: none`. This is going to be slow but useful.

Alternatively - we hide workspaces by detaching elements from DOM rather than using `display: none`. 

@tomalec?

**Comment by tomalec** [comment]
I would rather vote for editor checking visibility of show elements, rather that Launcher changing the behavior of workspaces for all users, to make tree view for editor more appealing. The question is what about nodes hidden otherwise? (ShadowDOM distribution, other CSS rules)

**Comment by warpech** [comment]
The only simple solution for the hidden workspaces proble,m that comes to my mind, is to run check if the tree root `juicy-tile-list`s, or their DOM ancestors, are not `display: none`.

But I think this is not a problem anymore, since the tree shows up in collapsed state by default.

This is offtopic anyway. What about the main topic of this issue? @tomalec do you suggest to keep "Unhide all" logic where it is right now and close this issue?

**Comment by tomalec** [comment]
Yes, I would suggest to leave it in `juicy-tile-editor`. If we really need we could make `unhideAll` sugar method in `juicy-tile-list` that will unhide all items from this list, but I think https://github.com/Juicy/juicy-tile-editor/blob/gh-pages/src/juicy-tile-editor.js#L615 is not a big deal for editor, and thanks to that it gets full controll when do (aggregated) refresh/repack

**Comment by warpech** [comment]
Closing then as Won't fix, thanks everyone for the opinions :)
