### ISSUE TITLE
The left sidebar does not stretch to content height

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Launcher#149]
There is a blank space below the left sidebar after scrolling:

![bug](https://cloud.githubusercontent.com/assets/566463/9229236/660f55c8-411c-11e5-8212-a5e153d1245d.gif)

It is clearly connected with `juicy-tile-grid`, but I don't understand how. @miyconst could you investigate that?

**Comment by miyconst** [comment]
This happens because the `juicy-tile` which contains the app store has no items on page load, and it's height being calculated as `0px`.  The content inside the tile is displayed as `overflow: visible`, this is why it does not stretch it's parent.

This issue could be solved with:
- default styles `height: 1, heightDynamic: true`.
- add background to `<body>` so it will look like the left panel goes to the very bottom.

**Comment by warpech** [comment]
I guess this will be enough:

> default styles `height: 1, heightDynamic: true`

Let's not change the background because that would only mask the problem, not fix it

**Comment by miyconst** [comment]
Added default styles to the AppStoreClient, the issue should be fixed.
